
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  notifications.argoproj.io/subscribe.slack: debug-infra
resources:
  - external-dns.yaml
  - external-secrets.yaml
  - gigaCI.yaml
  - prometheus.yaml
  - loki.yaml
  
